-- AlterTable
ALTER TABLE "SensitiveSiteOsmCache" ADD COLUMN     "maxLat" DOUBLE PRECISION,
ADD COLUMN     "maxLng" DOUBLE PRECISION,
ADD COLUMN     "minLat" DOUBLE PRECISION,
ADD COLUMN     "minLng" DOUBLE PRECISION;
